---
abstract: 'Non-invasive testing of subroutines within Perl programs'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-GlassBox-Heavy
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Devel::LexAlias: 0
  Devel::Symdump: 0
  File::Slurp: 0
  PadWalker: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
